# Generated by Django 5.2.4 on 2025-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_namer', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
