# Generated by Django 5.2.4 on 2025-07-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_details',
            old_name='customer_id',
            new_name='checkout_id',
        ),
    ]
