# Generated by Django 5.2.4 on 2025-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapplication', '0002_rename_customer_id_payment_details_checkout_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_details',
            old_name='customer_namer',
            new_name='customer_id',
        ),
    ]
