# Generated by Django 5.2.4 on 2025-07-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapplication', '0003_rename_customer_namer_payment_details_customer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment_details',
            new_name='payment_details_cus',
        ),
    ]
